Feature branch: Home page and About page
nouman17610/developers-meetup pull request #1
Opened 2023-08-02 18:49 UTC by nouman17610

I implemented the following tasks

- Home page responsive design
- About page responsive design
- Hamburger menu on mobile screen
- Dynamic speakers posts

2023-08-02 21:12 UTC, laiifuu requested changes
## Hi @nouman17610 :wave: 

Good job so far!
There are some issues that you still need to work on but you are almost there!

![cat-driving-serious](https://github.com/nouman17610/developers-meetup/assets/93520178/243753a7-bf6b-4b88-8f25-8f2caffb4520)


## Highlights
- [x] Green linters check :heavy_check_mark: 
- [x] Descriptive PR summary and title :heavy_check_mark: 
- [x] Great commit messages :heavy_check_mark: 
- [x] Speakers section dynamically loaded with JS :heavy_check_mark: 
- [x] Nice use of semantic elements :+1: 

## Required Changes ♻️
- [ ] Nice work on the header :+1: It would be great if you could add some spacing to adjust the nav container in mobile view because the burger menu and the logo are stuck to the edges of the screen: 
    - Your design: 
    ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/948e897b-6d23-4404-a540-84a11834e899)
    - The template: 
    ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/595688ba-a090-45dc-b5f1-fcf397f853f6)

- [ ] Nice work done on the header :+1: However there are some issues you still need to work on: 
    - The text in the black bar at the top is supposed to be white,
    - The `Campaign` button text is supposed to be orange,
    - There's an `x` that's appearing in the middle of the white navigation bar that should be removed 
        - You design: 
        ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/961b0976-7490-4330-ba63-f980984cf262)
         - The template: 
         ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/e5c5fc21-94d6-41ec-ae4b-58a120305826)

- [ ] Nice work done on the `Main Topics` sec tion :+1: However there are a few things you need to adjust: 
    - There should be a small orange bar dividing the title `Main Topics` and the topics cards, 
    - There should be a hover effect when hovering over the topics cards, that turns the border of the cards to white, 
    - The text `SEE THE WHOLE PROGRAM` should be underlined, 
    - There should be more space at the top and bottom of the section,
        - Your design: 
        ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/4af379fc-0f4b-4aad-9ec6-830c7a7eec04)
        - The template: 
        ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/ed63cef0-65ca-44f3-99f3-4fa43101d3ae)

- [ ] In mobile view for the `Main Topics` section: 
    - There should be more spacing between the topics cards, 
    - `See the whole program` should be replaced with an orange button, 
        - Your design: 
        ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/20e63fdb-e61f-43fd-894e-6c9cbfd7f9e2)
        - The template: 
        ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/aa39ec4c-f83f-4a15-8110-3fa18301b5ab)

- [ ] In the main speakers section, there should be a small orange bar separating the title of the section, and the speakers: 
    - Your design: 
    ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/41a745bc-59fd-4b89-a4d7-17c29cdc2b68)
    - The template: 
    ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/6d1b4df3-1efb-4c4a-901e-7eaf7dd278d9)

- [ ] In the main speakers section, the image for the first speaker doesn't appear: 
![image](https://github.com/nouman17610/developers-meetup/assets/93520178/9ced75a8-1a79-4a2b-ae3d-37e6fd3c0653)

- [ ] For the first section in the `About` page, there should be a line of text above the big title in mobile view: 
    - Your design: 
    ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/11a566f7-b489-4d18-862b-c438ed73d55a)

    - The template: 
    ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/448d4a55-3cbc-4464-8b9f-c66969e62a20)

- [ ] There's an issue with the width of the page since i can horizontally scroll the page: 
![image](https://github.com/nouman17610/developers-meetup/assets/93520178/827de3ad-be4e-453e-9296-9e3c7104ee28)
![image](https://github.com/nouman17610/developers-meetup/assets/93520178/f06d68a0-1807-40c5-93b3-ae0f5092220b)

- [ ] As mentionned in the requirements, you are supposed to personalize the content of your page based on the theme you chose, so for the the second section of the `About` page, you should change its content but keep the skeleton. You should also add a small orange bar beneath the title of the section to match the design:
Your design: 
![image](https://github.com/nouman17610/developers-meetup/assets/93520178/3039faa5-04fd-48a6-844f-6a1aba5e6dbe)

- [ ] For the third section, you should also personalize the content of the title and the text beneath it, and add a small orange bar under the section's title: 
Your design: 
![image](https://github.com/nouman17610/developers-meetup/assets/93520178/3ede4c90-ee3d-4f6e-b1d5-e7b0c1bfb858)

In the mobile view, the images are taking a larger space then they should, kindly fix this issue: 
    - Your design: 
    ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/e4ebf983-e257-4a4e-a562-ad052b2be519)
    - The template: 
    ![image](https://github.com/nouman17610/developers-meetup/assets/93520178/93d23deb-28ce-443a-a221-0e49b4637c4a)

- [ ] Nice job using semantic tags in your web pages :+1:  It would be even better if you could use the semantic `article` tag for your topic boxes in the `Home` page.




_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 21:12 UTC, laiifuu commented on README.md
> +
As requested in the [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#:~:text=The%20Creative%20Commons%20license%20of%20the%20design%20requires%20that%20you%20give%20appropriate%20credit%20to%20the%20author.%20Therefore%2C%20you%20must%20do%20it%20in%20the%20README%20of%20your%20project.), you should give proper credit to the author behind the original design, [Cindy Shin](https://www.behance.net/adagio07).

2023-08-02 21:12 UTC, laiifuu commented on README.md
> +    - [🚀 Live Demo](#live-demo)
As mentionned in the [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#:~:text=Deploy%20the%20project%20and%20check%20to%20make%20sure%20everything%20works%20as%20planned.), you should deploy your project using `GitHub Pages`. Once you do that, add the link to your deployed project to your `README`.

2023-08-02 21:15 UTC, laiifuu commented
I'm sorry i accidentally submitted the review before finishing it, please wait before going ahead with making changes :pray:

2023-08-02 21:17 UTC, nouman17610 commented
> I'm sorry i accidentally submitted the review before finishing it, please wait before going ahead with making changes 🙏

@laiifuu 
Okay, no problem. Please in your final changes, identify the selector that needs to display none to remove the cross button from the desktop version.

2023-08-02 22:04 UTC, laiifuu commented
> > I'm sorry i accidentally submitted the review before finishing it, please wait before going ahead with making changes pray
> 
> @laiifuu Okay, no problem. Please in your final changes, identify the selector that needs to display none to remove the cross button from the desktop version.

It's this element: 
![image](https://github.com/nouman17610/developers-meetup/assets/93520178/11556659-953c-4ccd-bfed-4781f9c7a44a)

2023-08-03 10:37 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @nouman17610 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Content is uniquely tailored ✔
- UI is looking good ✔
- Correct use of GitHub Flow ✔
- Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 10:37 UTC, AbelG101 commented on style.css
> +}
- [ ] As mentioned previously please make sure to add some vertical spacing between the cards in the "Main Topics" section in the mobile version as shown in the Behance design.
- Your design:
  ![image](https://github.com/nouman17610/developers-meetup/assets/104968236/df64641d-0b77-4bf5-a163-a9960b8253ee)
- Behance design: 
  ![](https://user-images.githubusercontent.com/93520178/257944932-aa39ec4c-f83f-4a15-8110-3fa18301b5ab.png)

2023-08-03 10:37 UTC, AbelG101 commented on style.css
> +}
- [ ] As mentioned previously the width in the About page is overflowing and creating a scroll behavior so I'd advise you fix it as it leads to a bad UX.
- Here's how it looks:
  ![FtIBjCsD1R](https://github.com/nouman17610/developers-meetup/assets/104968236/9206f053-aff4-46e2-ad14-abeddecd4fd7)

2023-08-03 12:43 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @nouman17610,

✔️ No overflows and nice design

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 18:22 UTC, merged